[runtime]
log_level="WARNING"  # the system log level of dlt
dlthub_telemetry = true

[sources.filesystem]
bucket_url = "s3://bronze"
file_glob = "default/event_streaming/metrics/year=2026/month=03/day=16/hour=12/*.json.gz"

[destination.filesystem]
bucket_url = "s3://silver/default"
layout="{table_name}/year={YYYY}/month={MM}/day={DD}/{load_id}.{file_id}.{ext}"