[sources.filesystem.credentials]
aws_access_key_id = ""
aws_secret_access_key = ""
aws_session_token = ""
region_name = "us-west-2"

[destination.filesystem.credentials]
aws_access_key_id = ""
aws_secret_access_key = ""
aws_session_token = ""
region_name = "us-west-2"